import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
import { useRef } from "react";
import AvailableRooms from "../components/AvailableRooms";

const Home: NextPage = () => {
  const router = useRouter();

  const utils = trpc.useContext();
  const { mutate: createRoomMutation, isLoading } = trpc.useMutation(
    ["room.createRoom"],
    {
      onSuccess: () => {
        utils.invalidateQueries();
        router.push("rooms/" + nameRef?.current?.value);
      },
    }
  );

  function createRoom() {
    const nameVal = nameRef?.current?.value;
    if (nameVal) {
      createRoomMutation({ name: nameVal });
    }
  }

  const nameRef = useRef<HTMLInputElement>(null);

  return (
    <>
      <Head>
        <title>netracer.js</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center bg-gradient-to-br from-violet-900 to-gray-900 justify-center h-screen">
        <div className="flex flex-col items-center w-1/4 ">
          <h1 className="py-2 text-white font-semibold text-5xl text-center ">
            Netracer.js
          </h1>
          <div className="py-8 flex w-full">
            <div className="relative z-0 w-full">
              <input
                ref={nameRef}
                type="text"
                id="floating_standard"
                className="block py-2.5 text-white px-0 w-full text-sm bg-transparent border-0 border-b-2 border-white appearance-none focus:outline-none focus:ring-0 focus:border-violet-500 peer"
                placeholder=" "
              />
              <label
                htmlFor="floating_standard"
                className="absolute text-sm text-white duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-violet-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
              >
                room name
              </label>
            </div>
          </div>

          {isLoading ? (
            <button
              className="bg-violet-500 w-full py-3 mt-6 rounded-md px-5 text-white font-bold text-sm"
              onClick={createRoom}
            >
              <svg
                aria-hidden="true"
                role="status"
                className="inline w-4 h-4 mr-2 text-gray-200 animate-spin dark:text-gray-600"
                viewBox="0 0 100 101"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                  fill="currentColor"
                />
                <path
                  d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                  fill="#1C64F2"
                />
              </svg>
              loading
            </button>
          ) : (
            <button
              className="bg-violet-500 w-full py-3 mt-6 rounded-md px-5 text-white font-bold text-sm"
              onClick={createRoom}
            >
              create room
            </button>
          )}
        </div>
        <div className="w-1/2 mt-12">
          <AvailableRooms />
        </div>
      </main>
    </>
  );
};

export default Home;
